#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
# list all files; cd to team-platform; list those files | prepend doc/team-platform/ to each file; cd back | remove lines w/ spaces | remove last line
# { git ls-files;   cd ../team-platform; (git ls-files    | awk '{print "doc/team-platform/" $0}');  cd -; } | sed '/\s/,/^/d'        | sed -e '$ d' | \
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
